{% set name = "rtxpy" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rtxpy-{{ version }}.tar.gz
  sha256: 7f47c3d1cb161220ca2a99ba52c6f0c15435626d8f90b2286d5ffd6260cb1f45

build:
  number: 2
  skip: true   # [py<37]
  skip: true   # [osx]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.10
  host:
    - pip
    - python
  run:
    - numpy >=1.16
    - python

test:
  imports:
    - rtxpy
    - rtxpy.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/makepath/rtxpy
  summary: Ray tracing using CUDA accessible from Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brendancol
    - ianthomas23
