{% set name = "rtxpy" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rtxpy-{{ version }}.tar.gz
  sha256: cf6486a404b0f7997679a0013100786f43fa23c4816ab59e078603f1f5713eba

build:
  number: 0
  skip: true  # [osx]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - make  # [unix]
  host:
    - pip
    - python
    - setuptools
  run:
    - numpy >=1.16
    - python

test:
  imports:
    - rtxpy
    - rtxpy.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/makepath/rtxpy
  summary: Ray tracing using CUDA accessible from Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brendancol
    - ianthomas23
